name: upcbolsillo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2 #manejador de estados
  google_fonts: ^6.2.1
  equatable: ^2.0.7 #Permite realizar una comparacion de los objetos de manera mas profunda (Permite hacer testing)
  http: ^1.3.0 # Conectar con proveedor - Apis
  local_auth: ^2.3.0 # Acceso Biometrico
  shared_preferences: ^2.5.3
  # intl: ^0.18.0 #Conversion de idiomas, enteros, fechas
  awesome_dialog: ^3.2.1 #Dialogos
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0 #obtener version code de la app
  connectivity_plus: ^6.1.3 # Verifica a que tipo de red esta conectado
  device_info_plus: ^11.3.3 #Informacion del cell,Version Sistema Operatvivo
  network_info_plus: ^6.1.3 #Obtener ip del celular (se deben asiganr permisos para IOS)
  cached_network_image: ^3.4.1 #Muestra imagenes desde internet y las guarda en cache
  flutter_speed_dial: ^7.0.0 #Botones flotantes, utilizado para el menu (Cerrar sesion y mas)
  permission_handler: ^12.0.0+1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)
  image: ^4.5.4 #Para trabajar con imagenes de la galeria
  image_picker: ^1.1.2 #Obtener img de la camara o galeria
  share_plus: ^10.1.4 #Compartir aplicacion
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  flutter_polyline_points_plus: ^3.0.0
  polylabel: ^1.0.1
  flutter_dotenv: ^5.2.1 #leer .env
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  another_flushbar: ^1.12.30

  #vibration: ^1.7.6 #vibracion device
  location: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0 #ubicacion Gps, del dispositivo #error en la actualizacion 8.0.1 No named parameter with the name 'desiredAccuracy'.


  dropdown_search: ^6.0.2 #Combo con busqueda
  firebase_in_app_messaging: ^0.8.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  geolocator_android: ^5.0.1+1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_mi_upc.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/icon_mi_upc.png"
  flutter_lints: ^3.0.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icon/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
