name: upcbolsillo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2 #manejador de estados
  google_fonts: ^6.2.1
  equatable: ^2.0.7 #Permite realizar una comparacion de los objetos de manera mas profunda (Permite hacer testing)
  http: ^1.3.0 # Conectar con proveedor - Apis
  local_auth: ^2.3.0 # Acceso Biometrico
  shared_preferences: ^2.5.3
  awesome_dialog: ^3.2.1 #Dialogos
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0 #obtener version code de la app
  connectivity_plus: ^6.1.3 # Verifica a que tipo de red esta conectado
  device_info_plus: ^11.3.3 #Informacion del cell,Version Sistema Operatvivo
  network_info_plus: ^6.1.3 #Obtener ip del celular (se deben asiganr permisos para IOS)
  cached_network_image: ^3.4.1 #Muestra imagenes desde internet y las guarda en cache
  flutter_speed_dial: ^7.0.0 #Botones flotantes, utilizado para el menu (Cerrar sesion y mas)
  permission_handler: ^12.0.0+1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)
  image: ^4.5.4 #Para trabajar con imagenes de la galeria
  image_picker: ^1.1.2 #Obtener img de la camara o galeria
  share_plus: ^10.1.4 #Compartir aplicacion
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  flutter_polyline_points_plus: ^3.0.0
  polylabel: ^1.0.1
  flutter_dotenv: ^5.2.1 #leer ..env
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  another_flushbar: ^1.12.30
  location: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0 #ubicacion Gps, del dispositivo #error en la actualizacion 8.0.1 No named parameter with the name 'desiredAccuracy'.
  dropdown_search: ^6.0.2 #Combo con busqueda
  firebase_in_app_messaging: ^0.8.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  geolocator_android: ^5.0.1+1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_mi_upc.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/icon_mi_upc.png"
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/img/
    - assets/icon/

