// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmDe6mRQHEQXypMt1GnS_P1DIsBSZMSM',
    appId: '1:423096195082:web:174973dd95a681ccdee7f3',
    messagingSenderId: '423096195082',
    projectId: 'upcbolsillo-f425b',
    authDomain: 'upcbolsillo-f425b.firebaseapp.com',
    storageBucket: 'upcbolsillo-f425b.firebasestorage.app',
    measurementId: 'G-4S1F1XGWE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WnYAJsMRPltFlt3pfGWiMktnO-sA2dM',
    appId: '1:423096195082:android:d99a93da95140069dee7f3',
    messagingSenderId: '423096195082',
    projectId: 'upcbolsillo-f425b',
    storageBucket: 'upcbolsillo-f425b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-BK3uPh8phBmG5sz1G6-pko9rMXFyGg',
    appId: '1:423096195082:ios:9b78ec2fc94d6fc8dee7f3',
    messagingSenderId: '423096195082',
    projectId: 'upcbolsillo-f425b',
    storageBucket: 'upcbolsillo-f425b.firebasestorage.app',
    iosBundleId: 'com.example.upcbolsillo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-BK3uPh8phBmG5sz1G6-pko9rMXFyGg',
    appId: '1:423096195082:ios:9b78ec2fc94d6fc8dee7f3',
    messagingSenderId: '423096195082',
    projectId: 'upcbolsillo-f425b',
    storageBucket: 'upcbolsillo-f425b.firebasestorage.app',
    iosBundleId: 'com.example.upcbolsillo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmDe6mRQHEQXypMt1GnS_P1DIsBSZMSM',
    appId: '1:423096195082:web:61310856ffd17981dee7f3',
    messagingSenderId: '423096195082',
    projectId: 'upcbolsillo-f425b',
    authDomain: 'upcbolsillo-f425b.firebaseapp.com',
    storageBucket: 'upcbolsillo-f425b.firebasestorage.app',
    measurementId: 'G-X31LRLL3TT',
  );
}
